//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productid
    {
        public int Productid1 { get; set; }
        public string Productname { get; set; }
        public string Productprice { get; set; }
        public string Productimage { get; set; }
    }
}
